rxriskv_modified_icd10 <- tibble::frame_data(

  ~group,                                  ~regex,

  "alcohol_dependence",                    'N07BB0[1345]',
  "allergies",                             'R0[16]A[CDEX][0125][1-35-9]',
  "anti_coagulation_therapy",              'B01A[AB][01][0-69]',
  "anti_platelet_therapy",                 'B01AC[0-4679]',
  "anxiety",                               'N05BA[01][1246]',
  "arrhythmia",                            'C01[AB][A-D]0[13457]',
  "benign_prostate_hypertrophy",           'G04CA0[1-3]',
  "bipolar_disorder",                      'N0[35]A[EGHNX][01][1-49]',
  "chronic_heart_failure",                 'C0[39][ACD][AC][01][0-79]',
  "dementia",                              'N04D[AX]0[1-4]',
  "depression",                            'N06A[ABGX][012][0-689]',
  "diabetes",                              'A10[AB][A-HX][01][[:digit:]]',
  "end_stage_renal_disease",               '(B03XA0[1-3])|(A11CC0[1-4])',
  "epilepsy",                              'N03A[ABDEFGX][01][0-59]',
  "gastric_oesophageal_reflux_disorder",   'A02B[A-DX][015][1-6]',
  "glaucoma",                              'S01E[A-EX][05][1-5]',
  "gout",                                  'M04A[A-C]01',
  "hepatitis_c",                           'J05A[ABEX][0156][12457]',
  "hiv",                                   'J05A[EFGRX][016][[:digit:]]',
  "hyperkalaemia",                         'V03AE01',
  "hyperlipidemia",                        'C10[AB][ABCX][01][1-579]',
  "hypertension",                          'C0[239][ABDEKX][ABCX][01][1-9]',
  "hyperthyroidism",                       'H03AA0[12]',
  "angina",                                'C01DA[01][248]',
  "ischaemic_heart_disease_hypertension",  'C0[78][ACDF][ABG][01][1-7]',
  "inflammatory_bowel_disease",            'A07E[AC]0[1-46]',
  "liver_failure",                       	 'A06AD11',
  "malignancies",                          'L01[A-DX][A-EX][0-5][[:digit:]]',
  "malnutrition",                          'B05BA[01][03]',
  "migraine",                              'N02C[ACX]0[1-6]',
  "osteoporosis_pagets",                   'M05B[ABX]0[1-46-8]',
  "pain",                                  'N02A[ABEFGX][05][123569]',
  "inflammation_pain",                     'M01A[BCEHX][015][1-6]',
  "pancreatic_insufficiency",              'A09AA02',
  "parkinsons_disease",                    'N04[AB][ACDX]0[1-79]',
  "psoriasis",                             'D05[AB][ABX][05][12]',
  "psychotic_illness",                     'N05A[ABDEFHNX][01][1-68]',
  "chronic_airways_disease",               'R03[A-D][ABCKLX][01][[:digit:]]',
  "smoking_cessation",                     'N07BA0[1-3]',
  "steroid_responsive_diseases",           'H02AB(0[1246-9]|10)',
  "transplant",                            'L04AA[012][013468]',
  "tuberculosis0",                         'J04A[A-CKM]0[12456]'

) %>%
classifyr::as.classcodes()

devtools::use_data(rxriskv_modified_icd10, overwrite = TRUE)