---
title: "Benchmarking"
author: "Erik Bulow"
date: "2018-03-06"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Other ICD packages

The `coder` package is not the only (nor the first) R package aimed for ICD codes and comorbitity indexes.
Four additional packages (as listed below) were found as by 2016-04-14.

| Package             | Authour           | CRAN | GitHub                     | ICD versions                     |
|---------------------|-------------------|------|----------------------------|----------------------------------|
| icd                 | Jack Wasey        | X    | jackwasey/icd              | ICD9, ICD10, ICD-10-CM           |
| medicalrisk         | Patrick McCormick | X    | patrickmdnet/medicalrisk   | ICD-9-CM                         |
| comorbidities.icd10 | Max Gordon        |      | gforge/comorbidities.icd10 | ICD-9, ICD-10 (US/SWE)           |
| icdcoder            | Wade Cooper       |      | wtcooper/icdcoder          | ICD9, ICD-9-CM, ICD10, ICD-10-CM |


# Packages to compare

The `coder` package was initilly targeted for Swedish ICD data. Since Sweden (as opposed to USA)  use
mostly ICD-10 codes (in favour of ICD-9), the `medicalrisk` package is dropped from further comparisons.

The `icdcoder` package is not submitted to CRAN and inspection of the source code
reveals that the package does not yet seem to be ready for production release (it does for example
have some problems with its dependency packages). According to GitHub metrics, the development activity
has been quite limited and we therefore assume that the package is not under active development.
It is therefore not considered further within this comparison.


# Speed comparison

Calling functions from both `icd` and `comorbidities.icd10` by full reference (e. g. `package::fun`)
is problematic due to internal use of non standard evaluation. All compared packages are therefore
attached:



```r
library(coder)
```

```
## 
## Attaching package: 'coder'
```

```
## The following object is masked from 'package:methods':
## 
##     show
```

```r
suppressPackageStartupMessages(library(icd))
suppressPackageStartupMessages(library(comorbidities.icd10))

library(dplyr) # For data management
```

```
## 
## Attaching package: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

Benchmarking will be performed by calculating Elixhauser comorbidity classes based on ICD-10 codes by corresponding functions from the `icd`, `coder` and `comorbidities.icd10`
packages.

First some session info:


```r
si <- devtools::session_info(c("icd", "coder", "comorbidities.icd10"))
si$packages <- 
  si$packages %>% 
  filter(package %in% c("icd", "coder", "comorbidities.icd10")) %>% 
  select(-source)
si
```

```
## Session info -------------------------------------------------------------
```

```
##  setting  value                       
##  version  R version 3.4.3 (2017-11-30)
##  system   x86_64, mingw32             
##  ui       RStudio (1.0.136)           
##  language (EN)                        
##  collate  Swedish_Sweden.1252         
##  tz       Europe/Berlin               
##  date     2018-03-06
```

```
## Packages -----------------------------------------------------------------
```

```
##               package * version       date
## 1           coder *   0.4.3 2017-08-17
## 2 comorbidities.icd10 *   0.6.2 2016-08-11
## 3                 icd *   2.3.1 2017-10-12
```


We prepare a function to return a list with unevaluated calls to correspinding functions in specified packages:



```r
uneval_list <- function(pkgs = c("coder", "icd", "comorbidities.icd10")) {
  
  # Initiate a list of expressions to benchmark
  expr <- list()
  
  # Include function "classify" from package "coder"
  if ("coder" %in% pkgs) expr$coder <- substitute(
    
    classify(
      x, 
      by = "elix_icd10", 
      id = "id")
    )
  
  # Include function "icd_comorbid" from package "icd"
  if ("icd" %in% pkgs) expr$icd <- substitute( 
    
    icd_comorbid(
      dplyr::mutate(
        x, 
        id = as.character(id), 
        code = as.character(code)), 
      icd10_map_quan_elix, 
      visit_name = "id", 
      icd_name = "code")
    )
  
  # Include function "cmrbdt.calc" from package "comorbid.icd10"
  if ("comorbidities.icd10" %in% pkgs) expr$comorbidities.icd10 <- substitute( 
    
    cmrbdt.calc(
      x, 
      "id", 
      "code", 
      rep("10", nrow(x)), 
      cmrbdt.finder_fn = cmrbdt.finder.regex.elixhauser_Quan2005)
    )
  
  expr
}
```

We make another function to use for benchmarking


```r
bm <- function(pkgs = c("coder", "icd", "comorbidities.icd10"), ...) {
  microbenchmark::microbenchmark(list = uneval_list(pkgs), ...) %>%
  summary() %>% 
  knitr::kable(digits = 2)
}
```

We will use a randomly generated (totaly "fake"/non personal) dataset of size 10,000. This is of quite moderate size compared to real world data but will be sufficient for now.


```r
head(x <- dplyr::sample_n(coder::ex_icd10, 1e4, TRUE))
```

```
##                       id  code_date  code  hdia
## 1: el-Kaba, Abdul Maalik 2016-06-11  A191 FALSE
## 2:           Duin, River 2016-10-11  S822 FALSE
## 3:        Alvarez, Jacob 2016-05-14  N055 FALSE
## 4:   Linear, Christopher 2016-05-27 L309F FALSE
## 5:     Campbell, Kesnick 2016-02-20  M202 FALSE
## 6:         Smith, Ruasha 2016-05-05  N410 FALSE
```

The test data set does contain some codes beginning in "UA", "UB" and/or "UP". These are valid codes in the Swedish ICD 10 (2016) version but will not be recognised as such by `comorbidities.icd10`. They must therefore be excluded in order to proced:


```r
x <- dplyr::filter(x, !grepl("U[ABP]", code))
```

A data set of 9788 is now remaining.

Results in seconds:

```r
bm(times = 5, unit = "s")
```



|expr                |   min|    lq|  mean| median|    uq|   max| neval|cld |
|:-------------------|-----:|-----:|-----:|------:|-----:|-----:|-----:|:---|
|coder           |  0.07|  0.09|  0.12|   0.13|  0.13|  0.18|     5|a   |
|icd                 |  0.44|  0.45|  0.48|   0.45|  0.52|  0.54|     5|b   |
|comorbidities.icd10 | 13.15| 13.17| 13.22|  13.20| 13.28| 13.30|     5|c   |

Relative speed differences (with the fastest package used as reference):

```r
bm(times = 5, unit = "relative")
```



|expr                |    min|     lq|   mean| median|     uq|    max| neval|cld |
|:-------------------|------:|------:|------:|------:|------:|------:|-----:|:---|
|coder           |   1.00|   1.00|   1.00|   1.00|   1.00|   1.00|     5|a   |
|icd                 |   6.26|   6.19|   6.21|   6.39|   6.16|   6.09|     5|b   |
|comorbidities.icd10 | 186.21| 184.76| 174.84| 183.07| 179.92| 147.97|     5|c   |

We thus conclude that `coder` is faster than its competitors!





## Some reasons for speed differences

* Both `icd` and `coder` relies on matrices, while `comorbidities.icd10` uses data frames. Matrices are generally faster both due to its simpler structure (in this case logical/boolean while the data frame can have different types of classes for each column) and since matrices can be handled effectively through underlying (sub R) numerical C/C++/Fortran librarys such as LAPACK and BLAS.
* `coder` relies on compact regular expressions for classification. `comorbidities.icd10` can use regular expressions too (as done above) but the format is less compact. `icd` uses "raw" ICD-10 codes and "search for each possible parent of the given code, up to the three digit 'major'" (https://cran.r-project.org/web/packages/icd/vignettes/icd-10.html). (It might however be recorded as a side note that the `icd` package does rely on a (much) faster procedure when used with ICD-9 codes.)





## A note on RRO

Comparisons above shows result for the latest (released) R version (details shown above).

Even though we would not present any details here, the same benchamrk was performed also on the latest available version (3.2.4) of Revolution R Open (RRO) with both one and then multiple (4) cores. This was done on an Intel i7 machine (an architecture supposed to take full advantage of the Intel Math Kernel Library used by RRO). 

There were no relevant difference observed between one and 4 kernels. 
The `icd` package did perform better with RRO while `coder` and `comorbidities.icd10` were performing worse. The ranking among the packages were the same as above although the magnitude of the relative differneces were decreased between `coder` and `icd`.
 



# Output

It is abviously important also to compare the output of each function.
The basic output from all functions is a logical "table" with 31 columns (one for every Elixhauser comorbidity class) and one row for every patient.

`icd` and `coder` gives this "table" as a logical (boolean) matrix with patient id as row names. 
Each package does however sort their matrices in different orders by default.

The output from `comorbidities.icd10` is more complex. It is a list wherof one element is a data.frame (not a matrix as stated by the help page) with the desired output. The patient id is found as a factor column within the data frame.

We have to transfer the different outputs before they can be compared:


```r
all_output <- function(...) {
  
  # Limit the data
  x <- head(x, 100)
  
  # Calculae results for all functions
  res <- lapply(uneval_list(...), eval)
  
  # Transform results to comparable forms
  if (!is.null(res$coder)) 
    res$coder <-  res$coder[order(rownames(res$coder)), ]
  
  if (!is.null(res$comorbidities.icd10)) {
    id <- as.character(res$comorbidities.icd10$cmrbdt$id)
    x <- as.matrix(res$comorbidities.icd10$cmrbdt[, -1])
    rownames(x) <- id
    res$comorbidities.icd10 <- x[order(id), ]
  }
  res
}
```

We first conclude that column order is the same although class names are articulated slightly different (the `icd` package offer possibilities for more descriptive names as well):


```r
res <- all_output()

as.data.frame(lapply(res, colnames)) %>% 
  knitr::kable()
```



|coder                      |icd          |comorbidities.icd10 |
|:------------------------------|:------------|:-------------------|
|congestive heart failure       |CHF          |CHF                 |
|cardiac arrhythmias            |Arrhythmia   |ARRHYTHMIA          |
|valvular disease               |Valvular     |VALVE               |
|pulmonary circulation disorder |PHTN         |PULM.CIRC           |
|peripheral vascular disorder   |PVD          |PVD                 |
|hypertension uncomplicated     |HTN          |HTN.UNCOMP          |
|hypertension complicated       |HTNcx        |HTN.COMP            |
|paralysis                      |Paralysis    |PARALYSIS           |
|other neurological disorders   |NeuroOther   |NEURO.OTHER         |
|chronic pulmonary disease      |Pulmonary    |CHRONIC.PULM        |
|diabetes uncomplicated         |DM           |DM.UNCOMP           |
|diabetes complicated           |DMcx         |DM.COMP             |
|hypothyroidism                 |Hypothyroid  |HYPOTHYROID         |
|renal failure                  |Renal        |RENAL               |
|liver disease                  |Liver        |LIVER               |
|peptic ulcer disease           |PUD          |PUD                 |
|AIDS/HIV                       |HIV          |HIV                 |
|lymphoma                       |Lymphoma     |LYMPHOMA            |
|metastatic cancer              |Mets         |METS                |
|solid tumor                    |Tumor        |SOLID.TUMOR         |
|rheumatoid arthritis           |Rheumatic    |RHEUM               |
|coagulopathy                   |Coagulopathy |COAG                |
|obesity                        |Obesity      |OBESITY             |
|weight loss                    |WeightLoss   |WT.LOSS             |
|fluid electrolyte disorders    |FluidsLytes  |LYTES               |
|blood loss anemia              |BloodLoss    |ANEMIA.LOSS         |
|deficiency anemia              |Anemia       |ANEMIA.DEF          |
|alcohol abuse                  |Alcohol      |ETOH                |
|drug abuse                     |Drugs        |DRUGS               |
|psychoses                      |Psychoses    |PSYCHOSES           |
|depression                     |Depression   |DEPRESSION          |


We hope to have achieved the same result for each patient and each comorbidity class. 

```r
different <- res$coder != res$icd | res$icd != res$comorbidities.icd10
```
Were there any differences observed? `any(different)` says: FALSE (which is intended)!







